-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY='인문' 
AND (PUBLISHED_DATE < '2022-01-01' AND PUBLISHED_DATE > '2020-12-31')
ORDER BY PUBLISHED_DATE ASC